import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { ContactProvider } from "@/context/ContactContext"; 
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Leste Contact",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
          <ThemeProvider attribute="class" defaultTheme="dark">
            <ContactProvider>
              {children}
            </ContactProvider>
          </ThemeProvider>
        </body>
      </html>
    );
}